### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by alexgillcma**
* fix bool_url_does_not_contain
* fix ElementSelene not json serializable error

### CODE REVIEW

**Comment by dayalstrub-cma** [comment]
@alexgillcma is this ready to review? and what issues is it linked to?

**Comment by alexgillcma** [comment]
@dayalstrub-cma two linked issues - PR only includes a fix for one of them at the mo. @JonatanBenarrochCMA let's find another time for a bit of selene pairing

**Comment by alexgillcma** [comment]
update 7/11 - identified problem with getting element scroll height - selenium didn't like the fact we're using our own subclass of selenium's WebElement. Fixed the element type to be in line with other scripts in selene-core -- looks like this was just overlooked when selene was developed.

**But** we're sitll getting an assertion error as the function is failing to scroll within an element - needs a bit more time to investigate

**Comment by dayalstrub-cma** [comment]
should we maybe split the PRs and fix the first problem at least?

**Comment by alexgillcma** [comment]
@dayalstrub-cma @JonatanBenarrochCMA - have commented out the failing test, so this PR should just fix the first issue. Can pick up the issues with scrolling elements in a new PR

would appreciate a review on this one so we can get it merged

**Review by JonatanBenarrochCMA — APPROVED** [review]
LGTM, although it looks like my approval isn't enough.

**Review by dayalstrub-cma — APPROVED** [review]

**Comment by dayalstrub-cma** [comment]
@JonatanBenarrochCMA you'r right. we removed write access from everyone from selene to ensure people remembered it was public, but i think we need to revisit this now that it's been a while! as it's a headache.

**Comment by dayalstrub-cma** [comment]
@alexgillcma is this worth a small CHANGELOG update, even if we don't release?

**Pull request merged**
